name: Sync Orders

on:
  schedule:
    - cron: '*/59 * * * *'  # Ejecutar cada 59 minutos
  workflow_dispatch:  # Permite ejecutar manualmente

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run sync script
        env:
          COSHOWROOM_LOGINURL: ${{ secrets.COSHOWROOM_LOGINURL }}
          COSHOWROOM_EMAIL: ${{ secrets.COSHOWROOM_EMAIL }}
          COSHOWROOM_PASSWORD: ${{ secrets.COSHOWROOM_PASSWORD }}
          AUTH_TIENDANUBE: ${{ secrets.AUTH_TIENDANUBE }}
        run: node index.js