name: Update Status

env:
  COSHOWROOM_LOGINURL: ${{ secrets.COSHOWROOM_LOGINURL }}
  COSHOWROOM_EMAIL: ${{ secrets.COSHOWROOM_EMAIL }}
  COSHOWROOM_PASSWORD: ${{ secrets.COSHOWROOM_PASSWORD }}
  AUTH_TIENDANUBE: ${{ secrets.AUTH_TIENDANUBE }}

on:
  workflow_dispatch:

  repository_dispatch:
    types:
      - webhook
  schedule:
    - cron: '30 12 * * *'
    - cron: '30 18 * * *'
    - cron: '30 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: |
          npm install
          npm start
